Repository youngppl/turninggreen_core, pull requests merged in 2019-09, with the labels that each got.

#42 Update content
  app/assets/javascripts/challenges.js
  app/controllers/challenges_controller.rb
  app/controllers/themes_controller.rb
  app/helpers/challenges_helper.rb
  app/views/challenges/show.html.erb
Labels: content

#40 Settings testing
  app/views/devise/registrations/edit.html.erb
  spec/views/registrations/edit.html.erb_spec.rb
  spec/views/registrations/new.html.erb_spec.rb
Labels: add tests

#38 Navbar + Dashboard
  Gemfile
  Gemfile.lock
  app/assets/images/landing-page.svg
  app/assets/javascripts/application.js
  app/assets/javascripts/navbar.js
  app/assets/javascripts/users.js
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/themes.scss
  app/assets/stylesheets/users.scss
  app/assets/stylesheets/welcome.scss
  app/controllers/challenges_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/challenge.rb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_dashboard_navbar.html.erb
  app/views/layouts/_feedback_dropdown.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_notifications_dropdown.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/dashboard/_metric_logged_popup.html.erb
  app/views/themes/index.html.erb
  app/views/users/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/views/layouts/_dashboard_navbar.html.erb_spec.rb
Labels: enhancement

#43 edit dashboard
  app/assets/javascripts/navbar.js
  app/assets/javascripts/users.js
  app/assets/stylesheets/challenges.scss
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/themes.scss
  app/assets/stylesheets/users.scss
  app/assets/stylesheets/welcome.scss
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/challenge.rb
  app/views/layouts/_feedback_dropdown.html.erb
  app/views/layouts/application.html.erb
  app/views/users/show.html.erb
  config/initializers/devise.rb
Labels: enhancement

#44 Points
  app/assets/images/rootup-icon.png
  app/assets/images/rootup-logo.png
  app/assets/images/rootup-logo.svg
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/users.scss
  app/controllers/challenges_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/layouts/_dashboard_navbar.html.erb
  app/views/layouts/_header.html.erb
  app/views/users/show.html.erb
  db/migrate/20190908215613_add_points_to_users.rb
  db/migrate/20190909044036_add_level_to_user.rb
  db/schema.rb
Labels: enhancement

#39 Reflections
  app/assets/javascripts/reflections.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/challenges.scss
  app/assets/stylesheets/points.scss
  app/assets/stylesheets/reflections.scss
  app/assets/stylesheets/themes.scss
  app/assets/stylesheets/users.scss
  app/assets/stylesheets/welcome.scss
  app/controllers/challenges_controller.rb
  app/controllers/reflections_controller.rb
  app/controllers/welcome_controller.rb
  app/models/challenge.rb
  app/models/reflection.rb
  app/models/user.rb
  app/views/challenges/reflections.html.erb
  app/views/layouts/_dashboard_navbar.html.erb
  app/views/layouts/points/_points_earned_popup.html.erb
  app/views/layouts/points/_points_progress.html.erb
  app/views/welcome/privacy.html.erb
  config/routes.rb
  db/migrate/20190908010207_create_reflections.rb
  spec/models/reflection_spec.rb
Labels: enhancement

#46 implement cumulative graph
  app/assets/javascripts/users.js
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/views/users/show.html.erb
Labels: enhancement

#47 update default navbar
  app/assets/stylesheets/navbar.scss
  app/views/layouts/_default_navbar.html.erb
Labels: enhancement

#48 implement design fixes
  app/assets/javascripts/challenges.js
  app/assets/javascripts/users.js
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/reflections.scss
  app/assets/stylesheets/themes.scss
  app/assets/stylesheets/users.scss
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/views/challenges/RefCompleteCode
  app/views/challenges/reflections.html.erb
  app/views/challenges/show.html.erb
  app/views/layouts/_feedback_dropdown.html.erb
  app/views/layouts/_notifications_dropdown.html.erb
  app/views/themes/index.html.erb
  app/views/users/show.html.erb
  config/storage.yml
Labels: bug-fix

#49 Admin dash
  app/assets/javascripts/admin.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.scss
  app/controllers/admin_controller.rb
  app/views/admin/index.html.erb
  config/routes.rb
  db/migrate/20190923000548_add_admin_to_users.rb
  db/schema.rb
Labels: enhancement

#55 upgrade devise to remove security vulnerability
  Gemfile
  Gemfile.lock
Labels: bug-fix

#53 Completed challenges page
  app/assets/images/feedback-icon.svg
  app/assets/images/notifications-icon.svg
  app/assets/images/rootup-icon.png
  app/assets/javascripts/challenges.js
  app/assets/stylesheets/challenges.scss
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/reflections.scss
  app/controllers/challenges_controller.rb
  app/controllers/reflections_controller.rb
  app/helpers/challenges_helper.rb
  app/views/challenges/completed.html.erb
  app/views/layouts/_feedback_dropdown.html.erb
  app/views/layouts/_notifications_dropdown.html.erb
  app/views/layouts/challenges/_reflection_redirect_popup.html.erb
  app/views/layouts/challenges/_reflection_review_popup.html.erb
  config/routes.rb
Labels: enhancement

#54 improve font numbers
  app/assets/fonts/.gitkeep
  app/assets/fonts/varela-v10-latin-regular.eot
  app/assets/fonts/varela-v10-latin-regular.svg
  app/assets/fonts/varela-v10-latin-regular.ttf
  app/assets/fonts/varela-v10-latin-regular.woff
  app/assets/fonts/varela-v10-latin-regular.woff2
  app/assets/stylesheets/welcome.scss
  config/application.rb
Labels: enhancement

#56 add team page
  app/assets/images/team/jennifer.jpg
  app/assets/images/team/jenny.jpg
  app/assets/images/team/michelle.jpg
  app/assets/images/team/philip.jpg
  app/assets/images/team/ricky.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/team.scss
  app/controllers/team_controller.rb
  app/views/team/index.html.erb
  config/routes.rb
Labels: content
